### ISSUE TITLE
Create User -> Update User -> Not Found in Elasticsearch query

### ISSUE THREAD

**Issue by Alwin-Stegeman** [FusionAuth/fusionauth-java-client#8]
Hello, we are using FusionAuth 1.22.0 with Search: Elasticsearch and Database: PostgreSQL. We use the FusionAuth Java client (1.18.0) to communicate with the FusionAuth API. 

**What goes wrong is this:** 
* we create a new User via FusionAuthClient.createUser(UUID userId, UserRequest request)
* we add a Group membership for an existing Group for this User via FusionAuthClient.createGroupMembers(MemberRequest request)
* we refresh the index via FusionAuthClient..refreshUserSearchIndex()
* we retrieve the new User via FusionAuthClient.retrieveUser(UUID userId)
* we retrieve all Users in the Group we added the new User to via FusionAuthClient.retrieveGroup(UUID groupId) and the new User is included
* next, we update the new User (change name) via FusionAuthClient.updateUser(UUID userId, UserRequest request)
* we refresh the index via FusionAuthClient..refreshUserSearchIndex()
* then, we again retrieve all Users in the Group (as above) but now the new and updated User is NOT included !
* a GET query on the Elasticsearch index fusionauth_users to retrieve all Users in the Group yields the same result: the new and updated User is NOT included
* in the FusionAuth UI, the User is present with the new name and correct Group membership
* after doing a reindex in the FusionAuth UI via System > Reindex and again running the query (via Java client or directly on Elasticsearch index) yields the correct result
* however, repeating the above (adding and updating a User) yields the same results

So the question is whether this is a bug or whether we are doing something wrong?

**Comment by mooreds** [comment]
Hiya @Alwin-Stegeman , thanks for the issue.

A couple of things:

1. We recommend that you use the same version of the client library as the FusionAuth version (so 1.22 in this case). I'd have to look at the changes to see if there are any issues, but wanted to let you know that general guidance.
2. You shouldn't need to run `refreshUserSearchIndex` that often. Per https://fusionauth.io/docs/v1/tech/core-concepts/users/#reindex , you only need to run this in rare circumstances. In most cases, the index should refresh itself when changes occur.
3. Per the above point 2, can you try running these queries without refreshing the search index?

**Comment by voidmain** [comment]
Just a couple quick comments, the `refresh` is a bit different than the `reindex` and it is fine to run it if you need the search index to contain the latest data. @mooreds is correct that you shouldn't use it a ton though, only when needed. 

The steps that @Alwin-Stegeman listed look like they should be working fine. It could be a bug in the `updateUser` user step. That might not be correctly sending the group ids to Elastic.

My main question is if this is a multi-node setup. Specifically, is ElasticSearch multi-node? And secondarily, is FusionAuth in a multi-node setup and are you round-robining between FusionAuth nodes?

**Comment by mooreds** [comment]
Ah, my bad. Thanks for the clarification @voidmain . Here's the [flush documentation](https://fusionauth.io/docs/v1/tech/apis/users/#flush-the-search-engine) for anyone else reading.

**Comment by Alwin-Stegeman** [comment]
Thanks for thinking along @mooreds and @voidmain !

Here are some answers:
* we use a 1-node Elasticsearch cluster with FusionAuth
* setting the version of the FusionAuth Java Client equal to the version of FusionAuth (1.22.0) did not solve the issue
* removing the refresh of the Elasticsearch index after updating a User shows strange behavior: after changing a User's name it if found, but after changing it a second time it is not found. However, another 'lost' User was found when getting the Users for the Group after the second name change of the User. So it does seem to have an influence.
* removing the refresh index after creating a new User in the Group results in it not being found right after creation. This is the reason we do the refresh index.

As an alternative we could use PostgreSQL to store User data, but the FusionAuth API does not allow to GET all Users in a Group with this set-up. However, we could just query the fusionauth database since it contains a table group_members. But bypassing the FusionAuth API may not be a robust solution.

Other suggestions are welcome.

**Comment by mooreds** [comment]
@Alwin-Stegeman 

I'm a bit confused. I spent some time trying to replicate what you are doing.

It doesn't appear to me that pulling the group would give you the members of the group: https://fusionauth.io/docs/v1/tech/apis/groups/#retrieve-a-group indicates that only group attributes, not members, are returned.

Are you instead perhaps running a user search with a `queryString` of `memberships.groupId:...` ?

From my testing, it looks like using the `PUT` update method affects the elasticsearch index, even though it doesn't affect the underlying data (if you retrieve the user, the data is still in the database).

Can you test if `PATCH`ing the user, using the `patchUser` java client method, causes the same issue? It doesn't in my testing.

**Comment by mooreds** [comment]
It does look like a bug, so I filed https://github.com/FusionAuth/fusionauth-issues/issues/1087

**Comment by robotdan** [comment]
Is this the same as https://github.com/FusionAuth/fusionauth-issues/issues/932?

**Comment by Alwin-Stegeman** [comment]
@mooreds : Sorry. Indeed, instead of FusionAuthClient.retrieveGroup(UUID groupId) I meant FusionAuthClient.searchUsersByQuery(SearchRequest request) with queryString = "memberships.groupId:" + groupId;

If I use PATCH instead of PUT like this: FusionAuthClient.patchUser(UUID userId, Map<String, Object> request) with request.put("fullName", "newUserName") or as key "user.fullName" or "properties.fullName", then the user name is NOT changed in Elasticsearch. Is this the correct key to use in the Map? 

@robotdan : We do not change the Group membership of a User, but its name. After that it is not found when searching for all Users in the Group via the above Elasticsearch query.

**Comment by mooreds** [comment]
I believe you have to use this code to patch:

```
Map<String, Object> userMap = new HashMap(); userMap.put("fullName", "newName");
Map<String, Object> requestMap = new HashMap(); requestMap.put("user", userMap);
```

and then send `requestMap`.

Can you try that, please?

**Comment by Alwin-Stegeman** [comment]
@mooreds Indeed, that's what I use and it works fine.

**Comment by mooreds** [comment]
Great. Looks like this bug will be fixed in 1.23.4, coming out real soon now(tm).

**Comment by robotdan** [comment]
Version 1.24.0 is available, feel free to test and let us know if this version resolves your issue.

**Comment by mooreds** [comment]
@Alwin-Stegeman did 1.24.0 resolve the issue?

**Comment by mooreds** [comment]
Am closing this due to inactivity. Please re-open if the bug pops up again.
